### ISSUE TITLE
About strings sort

### ISSUE THREAD

**Issue by UlyssesWu** [marcussacana/KrKrZSceneManager#1]
PSB parsing is already implemented in my [FreeMote](https://github.com/UlyssesWu/FreeMote), including strings sort. And I have added basic support for non-emote PSBs (pimg/scn). I think a better way to implement your tool is to read PSB using FreeMote. After that you get all strings and you can simply modify them, then merge and build modified PSB.

**Comment by marcussacana** [comment]
Thx i will take a proper look after return of my travel, I want ask 2 things
1 - Support the MDF?
2 - If looks possible, I can copy your code? (I will give credits, of course)

**Comment by UlyssesWu** [comment]
1. Sorry but no for now... but if the MDF you said is just compressed PSB, I can add support to it.
2. Yes, just follow the LGPL license, besides using code you can also just import the dll or use git submodule.

**Comment by marcussacana** [comment]
Well, since i finished that my shitty psbanalyzer and he can shows like the original order, well, isn't perfect yet, as example he ignore a string that shows more than one time...
Anyway, now looks like the chronological sort, and because this I will close the issue.
And of course, since my tool don't allow change a duplicated string to 2 differente strings
and can brick with the psb v4 (i never saw one before) I think is better continue referring your tool in the readme
And your tool can extract the embedded resources of the psb...

Well, I have a proper reason to i don't just add your tool as nuget, 
It's because this KrKrScnEditor is just a dll to help translate the .scn text
and this ScnEditorGui as example how to use my dll...
So i think, if i include your tool as reference have no reason to my tool exists, right?
If your tool do everything, my .dll is useless and the example GUI too.

Well, thank you man! \*coff\* for the \*coff\*\*coff\*  nekopara live wallpaper \*coff\* too.
